services:
  - type: web
    name: bookmyseat
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn bookmyseat.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: bookmyseat.settings
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: True
