services:
  - type: web
    name: bookmyseat
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bookmyseat.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: bookmyseat.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: ALLOWED_HOSTS
        value: book-my-seat.onrender.com
