# Generated by Django 5.1.2 on 2025-03-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_seat_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
