# Generated by Django 5.1.2 on 2025-03-18 12:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_booking_show_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='show_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
