# Generated by Django 5.1.2 on 2025-03-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
