# Generated by Django 5.1.2 on 2025-05-15 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_booking_payment_status_booking_razorpay_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
